### ISSUE TITLE
Decoupling workflow steps

### ISSUE THREAD

**Issue by JHay0112** [sirlilpanda/kicad-project-template#9]
Decoupling setup and the different actions within the workflow e.g. Setup, ERC/DRC, BOM generation, Gerber generation. See #8 for motivation.

**Comment by sirlilpanda** [comment]
currently this is a pain because of the action to add and commit code not pulling recent changes as well as the action for setting up the kicad-cli taking about ~20 seconds to download its self and start. 

if there is someway to cache the kicad-cli action, and make the add and commit correctly pull down the repo each time before committing this would be an excellent addition.

i acknowledge the uploading these as artifacts would stop this issue, however i have left a left a reply [here](https://github.com/sirlilpanda/kicad-project-template/issues/8#issuecomment-2452809111) on why this might not be done.

**Comment by sirlilpanda** [comment]
in addition this would allow for separate badges for each pipeline stage to be created and shown in the readme

**Comment by JHay0112** [comment]
I've been looking at this a little bit --- as the commit history shows :'( --- the biggest challenge has been writing reusable workflows that actually work. GitHub's docs have been pretty cryptic and I've only really gone around in little circles. Main issue at the moment is passing the settings through a composite workflow. It complains about not expecting a mapping as an output (which is quite dissapointing for the settings).

**Comment by JHay0112** [comment]
Extra thought on the caching of the kicad-cli action. We could consider building our own and using one of the apt-cache actions there are, though I suspect this might not be a considerable speedup.

**Comment by sirlilpanda** [comment]
workflow steps have now been decoupled in the latest version
